<?php

use Illuminate\Database\Seeder;

class DelitoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    ////BASADO EN EL SISTEMA NACIONAL
    public function run()
    {
        DB::table('cat_delito')->insert([
            ['id' =>257,'nombre' => 'SIN INFORMACION'],
            ['id' =>1,'nombre' => 'LESIONES'],
            ['id' =>2,'nombre' => 'ASALTO'],
            ['id' =>3,'nombre' => 'VIOLENCIA FAMILIAR'],
            ['id' =>4,'nombre' => 'DESPOJO (TERRENO AGRICOLA O GANADERO)'],
            ['id' =>5,'nombre' => 'CONTRA LA PRESERVACION DEL LUGAR DE LOS HECHOS'],
            ['id' =>6,'nombre' => 'DELITOS DE LOS SERVIDORES PUBLICOS ART. 284'],
            ['id' =>7,'nombre' => 'HECHOS NO CONSTITUTIVOS DE DELITO'],
            ['id' =>8,'nombre' => 'INMERSION'],
            ['id' =>9,'nombre' => 'SIN DELITO'],
            ['id' =>10,'nombre' => 'ACOSO SEXUAL'],
            ['id' =>11,'nombre' => 'ASALTO A PIPA'],
            ['id' =>12,'nombre' => 'ASALTO A TRAILER'],
            ['id' =>13,'nombre' => 'ASALTO A TAXI'],
            ['id' =>14,'nombre' => 'ASALTO A PARTICULAR'],
            ['id' =>15,'nombre' => 'ASALTO A OTROS'],
            ['id' =>16,'nombre' => 'ROBO DE OBJETOS A INTERIOR DE VEHICULO SIN VIOLENCIA'],
            ['id' =>17,'nombre' => 'ABANDONO DE FAMILIARES'],
            ['id' =>18,'nombre' => 'ABIGEATO'],
            ['id' =>19,'nombre' => 'ABIGEATO EN GRADO DE TENTATIVA'],
            ['id' =>20,'nombre' => 'ABORTO'],
            ['id' =>21,'nombre' => 'ABUSO DE CONFIANZA'],
            ['id' =>22,'nombre' => 'ABUSO EROTICO-SEXUAL'],
            ['id' =>23,'nombre' => 'ADMINISTRACION FRAUDULENTA'],
            ['id' =>24,'nombre' => 'ALLANAMIENTO DE MORADA'],
            ['id' =>25,'nombre' => 'AMENAZAS'],
            ['id' =>26,'nombre' => 'ASALTO CAMINO VECINAL A VEHICULO'],
            ['id' =>27,'nombre' => 'ASALTO EN CAMINO VECINAL A CAMION REPARTIDOR'],
            ['id' =>28,'nombre' => 'ASALTO EN CAMINO VECINAL A TRANSEUNTE'],
            ['id' =>29,'nombre' => 'ASALTO EN CARRETERA A CAMION REPARTIDOR'],
            ['id' =>30,'nombre' => 'ASALTO EN CARRETERA A TRANSEUNTE'],
            ['id' =>31,'nombre' => 'ASALTO EN CARRETERA A VEHICULO'],
            ['id' =>32,'nombre' => 'ASALTO EN GRADO DE TENTATIVA'],
            ['id' =>33,'nombre' => 'ATAQUES A LA LIBERTAD DE REUNION Y EXPRESION'],
            ['id' =>34,'nombre' => 'BIGAMIA'],
            ['id' =>35,'nombre' => 'CALUMNIAS'],
            ['id' =>36,'nombre' => 'COACCION Y AMENAZAS'],
            ['id' =>37,'nombre' => 'COALICION'],
            ['id' =>38,'nombre' => 'COHECHO'],
            ['id' =>39,'nombre' => 'COHECHO EN GRADO DE TENTATIVA'],
            ['id' =>40,'nombre' => 'CONGESTION ETILICA'],
            ['id' =>41,'nombre' => 'CONSPIRACION'],
            ['id' =>42,'nombre' => 'CORRUPCION DE MENORES O INCAPACES'],
            ['id' =>43,'nombre' => 'DAÑOS'],
            ['id' =>44,'nombre' => 'DAÑOS CULPOSOS'],
            ['id' =>45,'nombre' => 'DAÑOS DOLOSOS'],
            ['id' =>46,'nombre' => 'DELITOS AMBIENTALES'],
            ['id' =>47,'nombre' => 'DELITOS CONTRA EL ESTADO CIVIL'],
            ['id' =>48,'nombre' => 'DELITOS CONTRA EL RESPETO A LOS MUERTOS'],
            ['id' =>49,'nombre' => 'DELITOS CONTRA LA FILIACION'],
            ['id' =>50,'nombre' => 'DELITOS CONTRA LA SEGURIDAD DEL TRANSITO DE VEHICULOS'],
            ['id' =>51,'nombre' => 'DELITOS CONTRA LA SEGURIDAD VIAL Y LOS MEDIOS DE TRANSPORTE'],
            ['id' =>52,'nombre' => 'DELITOS DE ABOGADOS, DEFENSORES Y LITIGANTES'],
            ['id' =>53,'nombre' => 'DESAPARICION DE PERSONAS'],
            ['id' =>54,'nombre' => 'DESOBEDIENCIA Y RESISTENCIA DE PARTICULARES'],
            ['id' =>55,'nombre' => 'DESPOJO'],
            ['id' =>56,'nombre' => 'EJERCICIO INDEBIDO O ABANDONO DE FUNCIONES PUBLICAS'],
            ['id' =>57,'nombre' => 'DELITOS ELECTORALES'],
            ['id' =>58,'nombre' => 'ENCUBRIMIENTO POR FAVORECIMIENTO'],
            ['id' =>59,'nombre' => 'ENCUBRIMIENTO POR RECEPTACION'],
            ['id' =>60,'nombre' => 'ENRIQUECIMIENTO ILICITO'],
            ['id' =>61,'nombre' => 'ESTRAGOS'],
            ['id' =>62,'nombre' => 'ESTUPRO'],
            ['id' =>63,'nombre' => 'EVASION DE PRESOS'],
            ['id' =>64,'nombre' => 'EXACCION ILEGAL'],
            ['id' =>65,'nombre' => 'EXTORSION'],
            ['id' =>66,'nombre' => 'FALSAS DENUNCIAS Y SIMULACION DE PRUEBAS'],
            ['id' =>67,'nombre' => 'FALSEDAD ANTE LA AUTORIDAD'],
            ['id' =>68,'nombre' => 'FALSIFICACION DE DOCUMENTOS'],
            ['id' =>69,'nombre' => 'FALSIFICACION DE SELLOS, LLAVES, MARCAS Y CONTRASEÑAS'],
            ['id' =>70,'nombre' => 'FRACCIONAMIENTO INDEBIDO'],
            ['id' =>71,'nombre' => 'FRAUDE'],
            ['id' =>72,'nombre' => 'FRAUDE PROCESAL'],
            ['id' =>73,'nombre' => 'ROBO'],
            ['id' =>74,'nombre' => 'HOMICIDIO'],
            ['id' =>75,'nombre' => 'HOMICIDIO CULPOSO'],
            ['id' =>76,'nombre' => 'HOMICIDIO DOLOSO'],
            ['id' =>77,'nombre' => 'HOMICIDIO DOLOSO: ARMA BLANCA'],
            ['id' =>78,'nombre' => 'HOMICIDIO DOLOSO: ARMA DE FUEGO'],
            ['id' =>79,'nombre' => 'HOMICIDIO DOLOSO:OTROS'],
            ['id' =>80,'nombre' => 'HOMICIDIO EN GRADO DE TENTATIVA'],
            ['id' =>81,'nombre' => 'HOMICIDIO POR ACCIDENTE DE TRANSITO'],
            ['id' =>82,'nombre' => 'INCESTO'],
            ['id' =>83,'nombre' => 'INCUMPLIMIENTO  DE LA OBLIGACION DE DAR ALIMENTOS'],
            ['id' =>84,'nombre' => 'INDUCCION O AYUDA AL SUICIDIO'],
            ['id' =>85,'nombre' => 'INDUCCION O AYUDA AL SUICIDIO EN GRADO DE TENTATIVA'],
            ['id' =>86,'nombre' => 'INTIMIDACION'],
            ['id' =>87,'nombre' => 'LENOCINIO Y TRATA DE PERSONAS'],
            ['id' =>88,'nombre' => 'LESIONES CULPOSAS'],
            ['id' =>89,'nombre' => 'LESIONES DOLOSAS'],
            ['id' =>90,'nombre' => 'LESIONES DOLOSAS: ARMA BLANCA'],
            ['id' =>91,'nombre' => 'LESIONES DOLOSAS: ARMA DE FUEGO'],
            ['id' =>92,'nombre' => 'LESIONES DOLOSAS: OTROS'],
            ['id' =>93,'nombre' => 'LESIONES EN GRADO DE TENTATIVA'],
            ['id' =>94,'nombre' => 'MALTRATO A MENORES'],
            ['id' =>95,'nombre' => 'MATRIMONIOS ILEGALES'],
            ['id' =>96,'nombre' => 'MOTIN'],
            ['id' =>97,'nombre' => 'OMISION DE AUXILIO'],
            ['id' =>98,'nombre' => 'OMISION DE AUXILIO A ATROPELLADOS'],
            ['id' =>99,'nombre' => 'OMISION DE CUIDADO'],
            ['id' =>100,'nombre' => 'OTRAS MUERTES NO DELICTIVAS'],
            ['id' =>101,'nombre' => 'OTROS ASALTOS'],
            ['id' =>102,'nombre' => 'PECULADO'],
            ['id' =>103,'nombre' => 'PELIGRO DE CONTAGIO'],
            ['id' =>104,'nombre' => 'PRIVACION DE LA LIBERTAD FISICA'],
            ['id' =>105,'nombre' => 'INCITACION A COMETER UN DELITO APOLOGIA DE ESTE O DE ALGUN VICIO'],
            ['id' =>107,'nombre' => 'QUEBRANTAMIENTO DE LA SANCION DE PRIVACION, SUSPENSION O INHABILITACION DE DERECHOS'],
            ['id' =>108,'nombre' => 'QUEBRANTAMIENTO DE SELLOS'],
            ['id' =>109,'nombre' => 'REBELION'],
            ['id' =>110,'nombre' => 'REVELACION DE SECRETOS'],
            ['id' =>111,'nombre' => 'ROBO A  OTROS'],
            ['id' =>112,'nombre' => 'ROBO A BANCO CON VIOLENCIA'],
            ['id' =>113,'nombre' => 'ROBO A BANCO SIN VIOLENCIA'],
            ['id' =>114,'nombre' => 'ROBO A CAMION REPARTIDOR CON VIOLENCIA CAMINO VECINAL'],
            ['id' =>115,'nombre' => 'ROBO A CAMION REPARTIDOR CON VIOLENCIA CARRETERA'],
            ['id' =>116,'nombre' => 'ROBO A CAMION REPARTIDOR CON VIOLENCIA ZONA URBANA'],
            ['id' =>117,'nombre' => 'ROBO A CAMION REPARTIDOR SIN VIOLENCIA CAMINO VECINAL'],
            ['id' =>118,'nombre' => 'ROBO A CAMION REPARTIDOR SIN VIOLENCIA CARRETERA'],
            ['id' =>119,'nombre' => 'ROBO A CAMION REPARTIDOR SIN VIOLENCIA ZONA URBANA'],
            ['id' =>120,'nombre' => 'ROBO A CASA HABITACION CON VIOLENCIA'],
            ['id' =>121,'nombre' => 'ROBO A CASA HABITACION SIN VIOLENCIA'],
            ['id' =>122,'nombre' => 'ROBO A NEGOCIACIONES CON VIOLENCIA'],
            ['id' =>123,'nombre' => 'ROBO A NEGOCIACIONES SIN VIOLENCIA'],
            ['id' =>124,'nombre' => 'ROBO A TRANSEUNTE CON VIOLENCIA CAMINO VECINAL'],
            ['id' =>125,'nombre' => 'ROBO A TRANSEUNTE CON VIOLENCIA CARRETERA'],
            ['id' =>126,'nombre' => 'ROBO A TRANSEUNTE SIN VIOLENCIA CAMINO VECINAL'],
            ['id' =>127,'nombre' => 'ROBO A TRANSEUNTE SIN VIOLENCIA CARRETERA'],
            ['id' =>128,'nombre' => 'ROBO A TRANSEUNTES CON VIOLENCIA ZONA URBANA'],
            ['id' =>129,'nombre' => 'ROBO A TRANSEUNTES SIN VIOLENCIA ZONA URBANA'],
            ['id' =>130,'nombre' => 'ROBO DE FRUTOS CON VIOLENCIA'],
            ['id' =>131,'nombre' => 'ROBO DE FRUTOS SIN VIOLENCIA'],
            ['id' =>132,'nombre' => 'ROBO DE VEHICULO CON VIOLENCIA CAMINO VECINAL'],
            ['id' =>133,'nombre' => 'ROBO DE VEHICULO CON VIOLENCIA CARRETERA'],
            ['id' =>134,'nombre' => 'ROBO DE VEHICULO CON VIOLENCIA ZONA URBANA'],
            ['id' =>135,'nombre' => 'ROBO DE VEHICULO SIN VIOLENCIA CAMINO VECINAL'],
            ['id' =>136,'nombre' => 'ROBO DE VEHICULO SIN VIOLENCIA CARRETERA'],
            ['id' =>137,'nombre' => 'ROBO DE VEHÍCULO SIN VIOLENCIA ZONA URBANA'],
            ['id' =>138,'nombre' => 'ROBO EN GRADO DE TENTATIVA'],
            ['id' =>139,'nombre' => 'SABOTAJE'],
            ['id' =>140,'nombre' => 'SECUESTRO'],
            ['id' =>141,'nombre' => 'SECUESTRO EN GRADO DE TENTATIVA'],
            ['id' =>142,'nombre' => 'SEDICION'],
            ['id' =>143,'nombre' => 'SUICIDIO EN GRADO DE TENTATIVA'],
            ['id' =>144,'nombre' => 'SUMERSION'],
            ['id' =>145,'nombre' => 'SUSTRACCION DE MENORES O INCAPACES'],
            ['id' =>146,'nombre' => 'SUSTRACCION DE MENORES O INCAPACES EN GRADO DE TENTATIVA'],
            ['id' =>147,'nombre' => 'TERRORISMO'],
            ['id' =>148,'nombre' => 'TRAFICO DE INFLUENCIA'],
            ['id' =>149,'nombre' => 'ULTRAJES A LA AUTORIDAD'],
            ['id' =>150,'nombre' => 'ULTRAJES A LA MORAL PUBLICA'],
            ['id' =>151,'nombre' => 'USO DE DOCUMENTO FALSO'],
            ['id' =>152,'nombre' => 'USURA'],
            ['id' =>153,'nombre' => 'USURPACION DE FUNCIONES'],
            ['id' =>154,'nombre' => 'USURPACION DE PROFESION'],
            ['id' =>155,'nombre' => 'VARIACION DE NOMBRE O DOMICILIO'],
            ['id' =>156,'nombre' => 'VEHICULO PUESTO A DISPOSICION DEL MINISTERIO PUBLICO'],
            ['id' =>157,'nombre' => 'VENTA O PROMESA DE VENTA INDEBIDA'],
            ['id' =>158,'nombre' => 'VIOLACION'],
            ['id' =>159,'nombre' => 'VIOLACION DE CORRESPONDENCIA'],
            ['id' =>160,'nombre' => 'VIOLACION DE LAS LEYES SOBRE INHUMACIONES Y EXHUMACIONES'],
            ['id' =>161,'nombre' => 'VIOLACION EN GRADO DE TENTATIVA'],
            ['id' =>162,'nombre' => 'VIOLACION ENTRE PARIENTES'],
            ['id' =>163,'nombre' => 'VIOLACION POR EQUIPARACION'],
            ['id' =>164,'nombre' => 'VIOLACION TUMULTUARIA'],
            ['id' =>165,'nombre' => 'HECHOS DELICTUOSOS NO ESPECIFICADOS'],
            ['id' =>166,'nombre' => 'ROBO DE OBJETOS A INTERIOR DE VEHICULO CON VIOLENCIA'],
            ['id' =>167,'nombre' => 'ASALTO A CAMION DE PASAJEROS'],
            ['id' =>168,'nombre' => 'ASALTO A CAMION DE CARGA'],
            ['id' =>169,'nombre' => 'ROBO CALIFICADO'],
            ['id' =>170,'nombre' => 'ROBO DE FLUIDO'],
            ['id' =>171,'nombre' => 'FRAUDE EN GRADO DE TENTATIVA'],
            ['id' =>172,'nombre' => 'LESIONES CALIFICADAS'],
            ['id' =>173,'nombre' => 'LESIONES MUTUAS'],
            ['id' =>174,'nombre' => 'HOMICIDIO CALIFICADO'],
            ['id' =>175,'nombre' => 'EXPOSICION DE MENORES E INCAPACES'],
            ['id' =>176,'nombre' => 'MANIPULACION GENETICA'],
            ['id' =>177,'nombre' => 'ALLANAMIENTO DE DESPACHO, OFICINA O CONSULTORIO'],
            ['id' =>178,'nombre' => 'VIOLACION DE LA INTIMIDAD PERSONAL'],
            ['id' =>179,'nombre' => 'DELITOS INFORMATICOS'],
            ['id' =>180,'nombre' => 'DISCRIMINACION DE PERSONAS'],
            ['id' =>181,'nombre' => 'TRAFICO DE MENORES'],
            ['id' =>182,'nombre' => 'RETENCION INDEBIDA DE COSA MUEBLE'],
            ['id' =>183,'nombre' => 'INSOLVENCIA FRAUDULENTA EN PERJUICIO DE ACREEDORES'],
            ['id' =>184,'nombre' => 'OPERACIONES CON RECURSOS DE PROCEDENCIA ILICITA'],
            ['id' =>185,'nombre' => 'MALTRATO'],
            ['id' =>186,'nombre' => 'INDUCCION A LA MENDICIDAD'],
            ['id' =>187,'nombre' => 'DELITOS COMETIDOS POR MEDICOS, AUXILIARES Y OTROS RELACIONADOS CON LA PRACTICA DE LA MEDICINA'],
            ['id' =>188,'nombre' => 'DELITOS COMETIDOS POR OTROS PROFESIONALES Y TECNICOS'],
            ['id' =>189,'nombre' => 'FALSIFICACION DE TITULOS Y CONTRA LA FE PUBLICA'],
            ['id' =>190,'nombre' => 'PORNOGRAFIA INFANTIL O DE INCAPACES'],
            ['id' =>191,'nombre' => 'ABUSOS DESHONESTOS'],
            ['id' =>192,'nombre' => 'RETENCION DE MENORES'],
            ['id' =>193,'nombre' => 'RETENCION DE MENORES EN GRADO DE TENTATIVA'],
            ['id' =>194,'nombre' => 'PEDERASTIA'],
            ['id' =>195,'nombre' => 'EXTORSION EN GRADO DE TENTATIVA'],
            ['id' =>196,'nombre' => 'ESPIONAJE CONTRA LAS INSTITUCIONES DE SEGURIDAD PUBLICA'],
            ['id' =>197,'nombre' => 'FEMINICIDIO'],
            ['id' =>198,'nombre' => 'VIOLACION ESPECIFICA'],
            ['id' =>199,'nombre' => 'VIOLACION ESPECIFICA AGRAVADA'],
            ['id' =>200,'nombre' => 'VIOLACION GENERICA AGRAVADA'],
            ['id' =>201,'nombre' => 'PEDERASTIA AGRAVADA'],
            ['id' =>202,'nombre' => 'ABUSO DE AUTORIDAD'],
            ['id' =>203,'nombre' => 'INCUMPLIMIENTO DE UN DEBER LEGAL'],
            ['id' =>204,'nombre' => 'ROBO AGRAVADO'],
            ['id' =>205,'nombre' => 'SECUESTRO EXPRESS'],
            ['id' =>206,'nombre' => 'DELITOS CONTRA LA SALUD'],
            ['id' =>207,'nombre' => 'ROBO ESPECIFICO'],
            ['id' =>208,'nombre' => 'ROBO GENERICO'],
            ['id' =>209,'nombre' => 'VIOLENCIA FISICA'],
            ['id' =>210,'nombre' => 'VIOLENCIA PSICOLOGICA'],
            ['id' =>211,'nombre' => 'EQUIPARACION AL SECUESTRO'],
            ['id' =>212,'nombre' => 'SIMULACION AL SECUESTRO'],
            ['id' =>213,'nombre' => 'FEMINICIDIO EN GRADO DE TENTATIVA'],
            ['id' =>214,'nombre' => 'TRATA DE PERSONAS'],
            ['id' =>215,'nombre' => 'VIOLACION GENERICA'],
            ['id' =>216,'nombre' => 'HOMICIDIO EN RIÑA'],
            ['id' =>217,'nombre' => 'PEDERASTIA 1er PARRAFO'],
            ['id' =>218,'nombre' => 'ROBO DE FRUTOS'],
            ['id' =>219,'nombre' => 'VIOLENCIA ECONOMICA O PATRIMONIAL'],
            ['id' =>220,'nombre' => 'VIOLENCIA OBSTETRICA'],
            ['id' =>221,'nombre' => 'VIOLENCIA INSTITUCIONAL'],
            ['id' =>222,'nombre' => 'VIOLENCIA LABORAL'],
            ['id' =>223,'nombre' => 'VIOLENCIA EN EL AMBITO EDUCATIVO'],
            ['id' =>224,'nombre' => 'NARCOMENUDEO'],
            ['id' =>225,'nombre' => 'GRAFITI ILEGAL'],
            ['id' =>226,'nombre' => 'ESTERILIDAD FORZADA'],
            ['id' =>227,'nombre' => 'MOVILIZACION DE SERVICIOS DE EMERGENCIA'],
            ['id' =>228,'nombre' => 'PERTURBACION DEL ORDEN PUBLICO'],
            ['id' =>229,'nombre' => 'ROBO DE VEHICULO'],
            ['id' =>230,'nombre' => 'PEDERASTIA EN GRADO DE TENTATIVA'],
            ['id' =>231,'nombre' => 'SECUESTRO AGRAVADO'],
            ['id' =>232,'nombre' => 'DESAPARCION FORZADA DE PERSONAS'],
            ['id' =>233,'nombre' => 'PEDERASTIA 2do PARRAFO'],
            ['id' =>234,'nombre' => 'REVELACION DE INFORMACION RESERVADA'],
            ['id' =>235,'nombre' => 'DELITOS COMETIDOS POR ACTOS DE MALTRATO O CRUELDAD EN CONTRA DE LOS ANIMALES'],
            ['id' =>236,'nombre' => 'VIOLENCIA EN EL AMBITO FAMILIAR'],
            ['id' =>237,'nombre' => 'PORNOGRAFIA'],
            ['id' =>238,'nombre' => 'ROBO DE MAQUINARIA (CABLES, TUBOS y OTROS OBJETOS DESTINADOS AL SERVICIO PUBLICO) SIN VIOLENCIA'],
            ['id' =>239,'nombre' => 'ROBO DE MAQUINARIA (CABLES, TUBOS y OTROS OBJETOS DESTINADOS AL SERVICIO PUBLICO) CON VIOLENCIA'],
            ['id' =>240,'nombre' => 'ROBO DE MAQUINARIA (TRACTORES) SIN VIOLENCIA'],
            ['id' =>241,'nombre' => 'ROBO DE MAQUINARIA (TRACTORES) CON VIOLENCIA'],
            ['id' =>242,'nombre' => 'ROBO DE MAQUINARIA (HERRAMIENTA INDUSTRIAL O AGRICOLA) SIN VIOLENCIA'],
            ['id' =>243,'nombre' => 'ROBO DE MAQUINARIA (HERRAMIENTA INDUSTRIAL O AGRICOLA) CON VIOLENCIA'],
            ['id' =>244,'nombre' => 'ROBO DE VEHICULO AUTOMOTOR (EMBARCACIONES PEQUEÑAS Y GRANDES) SIN VIOLENCIA'],
            ['id' =>245,'nombre' => 'ROBO DE VEHICULO AUTOMOTOR (EMBARCACIONES PEQUEÑAS Y GRANDES) CON VIOLENCIA'],
            ['id' =>246,'nombre' => 'ROBO DE VEHICULO AUTOMOTOR (MOTOCICLETA) SIN VIOLENCIA'],
            ['id' =>247,'nombre' => 'ROBO DE VEHICULO AUTOMOTOR (MOTOCICLETA) CON VIOLENCIA'],
            ['id' =>248,'nombre' => 'ROBO A TRANSEUNTE  EN ESPACIO ABIERTO AL PUBLICO CON VIOLENCIA'],
            ['id' =>249,'nombre' => 'ROBO A TRANSEUNTE  EN ESPACIO ABIERTO AL PUBLICO SIN VIOLENCIA'],
            ['id' =>250,'nombre' => 'ROBO A TRANSPORTISTAS CON VIOLENCIA'],
            ['id' =>251,'nombre' => 'ROBO A TRANSPORTISTAS SIN VIOLENCIA'],
            ['id' =>252,'nombre' => 'ROBO DE AUTOPARTES CON VIOLENCIA'],
            ['id' =>253,'nombre' => 'ROBO DE AUTOPARTES SIN VIOLENCIA'],
            ['id' =>254,'nombre' => 'PRIVACION DE LA LIBERTAD EN GRADO DE TENTATIVA'],
            ['id' =>255,'nombre' => 'ACOSO Y HOSTIGAMIENTO SEXUAL'],
            ['id' =>256,'nombre' => 'TORTURA']
        ]);
    }
}
