<?php

use Illuminate\Database\Seeder;

class MarcaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    ////BASADO EN EL SISTEMA NACIONAL
    public function run()
    {
        DB::table('cat_marca')->insert([
			['id' =>0,'nombre' => 'SIN INFORMACION'],
			['id' =>1,'nombre' => 'CHEVROLET'],
			['id' =>2,'nombre' => 'CHRYSLER'],
			['id' =>3,'nombre' => 'NISSAN'],
			['id' =>4,'nombre' => 'FORD'],
			['id' =>5,'nombre' => 'RENAULT'],
			['id' =>6,'nombre' => 'VOLKSWAGEN'],
			['id' =>7,'nombre' => 'DINA'],
			['id' =>8,'nombre' => 'INTERNATIONAL'],
			['id' =>9,'nombre' => 'TRACTOCAMION'],
			['id' =>10,'nombre' => 'MERCEDES BENZ'],
			['id' =>11,'nombre' => 'MOTOCICLETA'],
			['id' =>12,'nombre' => 'VAM'],
			['id' =>13,'nombre' => 'MOTOCICLETAS'],
			['id' =>14,'nombre' => 'DODGE'],
			['id' =>15,'nombre' => 'BMW'],
			['id' =>16,'nombre' => 'DATSUN'],
			['id' =>17,'nombre' => 'PORSCHE'],
			['id' =>18,'nombre' => 'HONDA'],
			['id' =>19,'nombre' => 'LAND ROVER'],
			['id' =>20,'nombre' => 'AUDI'],
			['id' =>21,'nombre' => 'PEUGEOT'],
			['id' =>22,'nombre' => 'INDETERMINADO'],
			['id' =>23,'nombre' => 'CATERPILLAR'],
			['id' =>24,'nombre' => 'CASE'],
			['id' =>25,'nombre' => 'FAMSA'],
			['id' =>26,'nombre' => 'FREIGHTLINER'],
			['id' =>27,'nombre' => 'TUNERA'],
			['id' =>28,'nombre' => 'TRAILERS MONTERREY/SULTANA/RAMIREZ'],
			['id' =>29,'nombre' => 'RAMBLER'],
			['id' =>30,'nombre' => 'JAGUAR'],
			['id' =>31,'nombre' => 'CARABELA'],
			['id' =>32,'nombre' => 'HARLEY DAVISON'],
			['id' =>33,'nombre' => 'KAWASAKI'],
			['id' =>34,'nombre' => 'DUCATI'],
			['id' =>35,'nombre' => 'TRIUNFO'],
			['id' =>36,'nombre' => 'SUZUKI'],
			['id' =>37,'nombre' => 'YAMAHA'],
			['id' =>38,'nombre' => 'VESPA'],
			['id' =>39,'nombre' => 'SANYANG'],
			['id' =>40,'nombre' => 'KENWORTH'],
			['id' =>41,'nombre' => 'AUTOCAR'],
			['id' =>42,'nombre' => 'WHITE'],
			['id' =>43,'nombre' => 'MACK'],
			['id' =>44,'nombre' => 'SCANIA'],
			['id' =>45,'nombre' => 'TOYOTA'],
			['id' =>46,'nombre' => 'VOLVO'],
			['id' =>47,'nombre' => 'FRUEHAUF'],
			['id' =>48,'nombre' => 'TAKT'],
			['id' =>49,'nombre' => 'FIAT'],
			['id' =>50,'nombre' => 'GMC'],
			['id' =>51,'nombre' => 'WILLYS'],
			['id' =>52,'nombre' => 'AMERICAN QUANTUM'],
			['id' =>53,'nombre' => 'ANDERSON MANUFACTURING'],
			['id' =>54,'nombre' => 'APRILIA'],
			['id' =>55,'nombre' => 'ASHOK LEYLAND'],
			['id' =>56,'nombre' => 'ATK'],
			['id' =>57,'nombre' => 'AUTOSAN'],
			['id' =>58,'nombre' => 'BAJAJ'],
			['id' =>59,'nombre' => 'BEALL CORPORATION'],
			['id' =>60,'nombre' => 'ACURA'],
			['id' =>61,'nombre' => 'AGUILA'],
			['id' =>62,'nombre' => 'ALFA ROMEO'],
			['id' =>63,'nombre' => 'ANGLIA'],
			['id' =>64,'nombre' => 'ARO'],
			['id' =>65,'nombre' => 'ASTON MARTIN'],
			['id' =>66,'nombre' => 'BENTRY'],
			['id' =>67,'nombre' => 'BETONE'],
			['id' =>68,'nombre' => 'BIG-TEX'],
			['id' =>69,'nombre' => 'BROWN'],
			['id' =>70,'nombre' => 'BUICK'],
			['id' =>71,'nombre' => 'CADILLAC'],
			['id' =>72,'nombre' => 'CANSA LS CENTURY'],
			['id' =>73,'nombre' => 'CAYTRASA'],
			['id' =>74,'nombre' => 'CITROEN'],
			['id' =>75,'nombre' => 'CLEMENT'],
			['id' =>76,'nombre' => 'COZAD'],
			['id' =>77,'nombre' => 'CRANE CARRIER'],
			['id' =>78,'nombre' => 'CROWN'],
			['id' =>79,'nombre' => 'CICLO BHOWGE'],
			['id' =>80,'nombre' => 'DAIHATSU'],
			['id' =>81,'nombre' => 'DELORIAN'],
			['id' =>82,'nombre' => 'DESOTO'],
			['id' =>83,'nombre' => 'DIAMON RADEO'],
			['id' =>84,'nombre' => 'DINALPIN'],
			['id' =>85,'nombre' => 'DINCO'],
			['id' =>86,'nombre' => 'DUESEMBERG'],
			['id' =>87,'nombre' => 'EAGLE'],
			['id' =>88,'nombre' => 'EL MEXICANO'],
			['id' =>89,'nombre' => 'ESCEPTRE'],
			['id' =>91,'nombre' => 'FERRARI'],
			['id' =>92,'nombre' => 'FLEXI'],
			['id' =>93,'nombre' => 'FNA-AM-937'],
			['id' =>94,'nombre' => 'FTE EARRIER'],
			['id' =>95,'nombre' => 'GEO'],
			['id' =>96,'nombre' => 'GUZZI'],
			['id' =>97,'nombre' => 'ECHIZO'],
			['id' =>98,'nombre' => 'GENDRIKSON'],
			['id' =>99,'nombre' => 'HIKARI'],
			['id' =>100,'nombre' => 'HOOBS'],
			['id' =>101,'nombre' => 'HYSTER'],
			['id' =>102,'nombre' => 'HYUNDAI'],
			['id' =>103,'nombre' => 'IGSA'],
			['id' =>104,'nombre' => 'INFINITI'],
			['id' =>105,'nombre' => 'INMETAL'],
			['id' =>106,'nombre' => 'ISUZU'],
			['id' =>107,'nombre' => 'ISUZU AMIGO'],
			['id' =>108,'nombre' => 'JEEP'],
			['id' =>109,'nombre' => 'KEOHRING'],
			['id' =>110,'nombre' => 'KIA SEPHIA'],
			['id' =>111,'nombre' => 'KIA SPORTAGE'],
			['id' =>112,'nombre' => 'KUMOTO'],
			['id' =>113,'nombre' => 'LAFORZA'],
			['id' =>114,'nombre' => 'LAMBORGHINI'],
			['id' =>115,'nombre' => 'LANCIA'],
			['id' =>116,'nombre' => 'LAYTON'],
			['id' =>117,'nombre' => 'LEXUS'],
			['id' =>118,'nombre' => 'LINCOLN'],
			['id' =>119,'nombre' => 'LORRAIN'],
			['id' =>120,'nombre' => 'LOTUS'],
			['id' =>121,'nombre' => 'MASSERATI'],
			['id' =>122,'nombre' => 'MAZDA'],
			['id' =>123,'nombre' => 'MERCURY'],
			['id' =>124,'nombre' => 'MERCUR SCORPIPO'],
			['id' =>125,'nombre' => 'MEX DE AUTOS NIELSON'],
			['id' =>126,'nombre' => 'MG'],
			['id' =>127,'nombre' => 'MITSUBISHI'],
			['id' =>128,'nombre' => 'MITSUBISHI CORDIA'],
			['id' =>129,'nombre' => 'MORRIS'],
			['id' =>130,'nombre' => 'NASH'],
			['id' =>131,'nombre' => 'NAVISTAR-4000'],
			['id' =>132,'nombre' => 'NIGHHAWK'],
			['id' =>133,'nombre' => 'OLDSMOBILE'],
			['id' =>134,'nombre' => 'OMNI INTEGRALES'],
			['id' =>135,'nombre' => 'OPEL'],
			['id' =>136,'nombre' => 'PANTHER'],
			['id' =>137,'nombre' => 'PEÑA MOTOR'],
			['id' =>138,'nombre' => 'PETERBILT'],
			['id' =>139,'nombre' => 'PLYMOUNTH'],
			['id' =>140,'nombre' => 'PLYMOUNTH SE VOYAGER'],
			['id' =>141,'nombre' => 'POLAR AMERICA'],
			['id' =>142,'nombre' => 'PONTIAC'],
			['id' =>143,'nombre' => 'PROWLER'],
			['id' =>144,'nombre' => 'RIVICA'],
			['id' =>145,'nombre' => 'ROCCSA'],
			['id' =>146,'nombre' => 'ROVER'],
			['id' =>147,'nombre' => 'SAAB'],
			['id' =>148,'nombre' => 'SATURN'],
			['id' =>149,'nombre' => 'SCALIBUR'],
			['id' =>150,'nombre' => 'SILVER'],
			['id' =>151,'nombre' => 'SOMEX OMNI'],
			['id' =>152,'nombre' => 'SPEED STER'],
			['id' =>153,'nombre' => 'STERLING'],
			['id' =>154,'nombre' => 'STUDEBAKER'],
			['id' =>155,'nombre' => 'STUZ'],
			['id' =>156,'nombre' => 'SUBARU'],
			['id' =>158,'nombre' => 'SUMMIT'],
			['id' =>159,'nombre' => 'TANSA'],
			['id' =>160,'nombre' => 'TIMPTE'],
			['id' =>161,'nombre' => 'TOY DOLY'],
			['id' =>163,'nombre' => 'VALIANT DUSTER'],
			['id' =>164,'nombre' => 'VIPSA CHASIS REF VEO'],
			['id' =>165,'nombre' => 'AVANTI'],
			['id' =>166,'nombre' => 'BULTACO'],
			['id' =>167,'nombre' => 'CHECKER'],
			['id' =>168,'nombre' => 'CONSOLIER'],
			['id' =>169,'nombre' => 'FWA'],
			['id' =>170,'nombre' => 'GREAT DAME 170'],
			['id' =>171,'nombre' => 'HUMMER'],
			['id' =>172,'nombre' => 'IUECO'],
			['id' =>173,'nombre' => 'LUFKIN'],
			['id' =>174,'nombre' => 'MAKE'],
			['id' =>175,'nombre' => 'MARMON'],
			['id' =>176,'nombre' => 'DESIGNLINE'],
			['id' =>177,'nombre' => 'OSHKOSH'],
			['id' =>178,'nombre' => 'REMOLQUES'],
			['id' =>179,'nombre' => 'ROLLS ROYCE'],
			['id' =>180,'nombre' => 'TS MACK'],
			['id' =>181,'nombre' => 'TRIUMPH'],
			['id' =>182,'nombre' => 'WESTERN STAR'],
			['id' =>183,'nombre' => 'WHITEGMC'],
			['id' =>184,'nombre' => 'YUGO'],
			['id' =>185,'nombre' => 'GM CANADA'],
			['id' =>186,'nombre' => 'DRYSDALE'],
			['id' =>187,'nombre' => 'DuraClass Body'],
			['id' =>188,'nombre' => 'EICHER'],
			['id' =>189,'nombre' => 'EL DORADO NATIONAL'],
			['id' =>190,'nombre' => 'ELC'],
			['id' =>191,'nombre' => 'ERF'],
			['id' =>192,'nombre' => 'EVO BUS'],
			['id' =>193,'nombre' => 'Exiss Trailers'],
			['id' =>194,'nombre' => 'E-Z Dumper'],
			['id' =>195,'nombre' => 'FACTORY'],
			['id' =>196,'nombre' => 'FalCan Industries'],
			['id' =>197,'nombre' => 'Falcon Trailer Works Inc'],
			['id' =>198,'nombre' => 'FEATHERLITE'],
			['id' =>199,'nombre' => 'PIAGGIO'],
			['id' =>200,'nombre' => 'ALLIANCE'],
			['id' =>201,'nombre' => 'ALTAMIRANO'],
			['id' =>202,'nombre' => 'ATLAS'],
			['id' =>203,'nombre' => 'VESPA CIAO'],
			['id' =>204,'nombre' => 'CARMEX'],
			['id' =>205,'nombre' => 'CROENLINE'],
			['id' =>206,'nombre' => 'DEL BRAVO CARROCERIA'],
			['id' =>207,'nombre' => 'FERBUSA'],
			['id' =>208,'nombre' => 'FERMON'],
			['id' =>209,'nombre' => 'HALCON'],
			['id' =>210,'nombre' => 'GOLD RUSH'],
			['id' =>211,'nombre' => 'GOLDEC HAMM'],
			['id' =>212,'nombre' => 'HENDRIKSON'],
			['id' =>213,'nombre' => 'HERO'],
			['id' =>214,'nombre' => 'ISLO'],
			['id' =>215,'nombre' => 'JIALING'],
			['id' =>216,'nombre' => 'LOZANO REMOLQUE'],
			['id' =>217,'nombre' => 'MINSK'],
			['id' =>218,'nombre' => 'MURREL'],
			['id' =>219,'nombre' => 'REMOSA'],
			['id' =>220,'nombre' => 'REPSO'],
			['id' =>221,'nombre' => 'SPORT COUPE'],
			['id' =>222,'nombre' => 'THOR'],
			['id' =>223,'nombre' => 'HIGHLAND'],
			['id' =>224,'nombre' => 'TRAIL MOVILE'],
			['id' =>225,'nombre' => 'Hurst Trailers -'],
			['id' =>226,'nombre' => 'UTILITY'],
			['id' =>227,'nombre' => 'VAUXHALL'],
			['id' =>228,'nombre' => 'WABASH'],
			['id' =>229,'nombre' => 'WAYNE'],
			['id' =>230,'nombre' => 'HARTFORD'],
			['id' =>231,'nombre' => 'GRANADER'],
			['id' =>232,'nombre' => 'SEAT'],
			['id' =>233,'nombre' => 'GENERAL MOTORS'],
			['id' =>234,'nombre' => 'DAIMLER BENZ'],
			['id' =>235,'nombre' => 'FARGO'],
			['id' =>236,'nombre' => 'MASA'],
			['id' =>237,'nombre' => 'IKARBUS'],
			['id' =>238,'nombre' => 'INDCAR'],
			['id' =>239,'nombre' => 'INDEPENDENCE'],
			['id' =>240,'nombre' => 'INDIAN'],
			['id' =>241,'nombre' => 'Interstate'],
			['id' =>242,'nombre' => 'IRISBUS'],
			['id' =>243,'nombre' => 'IRIZAR'],
			['id' =>244,'nombre' => 'ITALJET'],
			['id' =>245,'nombre' => 'IZH'],
			['id' =>246,'nombre' => 'J & R'],
			['id' =>247,'nombre' => 'JAWA'],
			['id' =>248,'nombre' => 'JELCZ'],
			['id' =>249,'nombre' => 'JORDAN'],
			['id' =>250,'nombre' => 'AC'],
			['id' =>251,'nombre' => 'AIXAM'],
			['id' =>252,'nombre' => 'ALPINE'],
			['id' =>253,'nombre' => 'ALVIS'],
			['id' =>254,'nombre' => 'ALLARD'],
			['id' =>255,'nombre' => 'AM GENERAL'],
			['id' =>256,'nombre' => 'ARMSTRONG SIDDLEY'],
			['id' =>257,'nombre' => 'ASA'],
			['id' =>258,'nombre' => 'AUBURN'],
			['id' =>259,'nombre' => 'AUSTIN'],
			['id' =>260,'nombre' => 'AUSTIN-HEALEY'],
			['id' =>261,'nombre' => 'AUTO UNION'],
			['id' =>262,'nombre' => 'AUTOBIANCHI'],
			['id' =>263,'nombre' => 'AUTOVAZ'],
			['id' =>264,'nombre' => 'AUVERLAND'],
			['id' =>265,'nombre' => 'BADGE'],
			['id' =>266,'nombre' => 'BEIJING'],
			['id' =>267,'nombre' => 'BENTLEY'],
			['id' =>268,'nombre' => 'BERKELEY'],
			['id' =>269,'nombre' => 'BITTER'],
			['id' =>270,'nombre' => 'BIZARRINI'],
			['id' =>271,'nombre' => 'BOND'],
			['id' =>272,'nombre' => 'BORGWARD'],
			['id' =>273,'nombre' => 'BRISTOL'],
			['id' =>274,'nombre' => 'BUGATTI'],
			['id' =>275,'nombre' => 'CATERHAM'],
			['id' =>276,'nombre' => 'CG'],
			['id' =>277,'nombre' => 'CISITALIA'],
			['id' =>278,'nombre' => 'CIZETA-MORODER'],
			['id' =>279,'nombre' => 'CLENET'],
			['id' =>280,'nombre' => 'CONSULIER'],
			['id' =>281,'nombre' => 'COOPER'],
			['id' =>282,'nombre' => 'CORBIN'],
			['id' =>283,'nombre' => 'COSTE'],
			['id' =>284,'nombre' => 'DACIA'],
			['id' =>285,'nombre' => 'DAEWOO'],
			['id' =>286,'nombre' => 'DAF'],
			['id' =>287,'nombre' => 'DAIMLER'],
			['id' =>288,'nombre' => 'DAX'],
			['id' =>289,'nombre' => 'DELA CHAPELLE'],
			['id' =>290,'nombre' => 'DELAHAYE'],
			['id' =>291,'nombre' => 'DKW'],
			['id' =>292,'nombre' => 'DONKERVOORT'],
			['id' =>293,'nombre' => 'EDRAN'],
			['id' =>294,'nombre' => 'ELVA'],
			['id' =>295,'nombre' => 'FACEL VEGA'],
			['id' =>296,'nombre' => 'FSO'],
			['id' =>297,'nombre' => 'GHIA'],
			['id' =>298,'nombre' => 'GIGLIATO'],
			['id' =>299,'nombre' => 'GILLET'],
			['id' =>300,'nombre' => 'GINETTA'],
			['id' =>301,'nombre' => 'GRANDIN'],
			['id' =>302,'nombre' => 'HAFEI'],
			['id' =>303,'nombre' => 'HEULIEZ'],
			['id' =>304,'nombre' => 'HILLMAN'],
			['id' =>305,'nombre' => 'HINDUSTAN'],
			['id' =>306,'nombre' => 'HINO'],
			['id' =>307,'nombre' => 'HISPANO-SUIZA'],
			['id' =>308,'nombre' => 'HOMMELL'],
			['id' =>309,'nombre' => 'HUDSON'],
			['id' =>310,'nombre' => 'IFA'],
			['id' =>311,'nombre' => 'IMPERIAL'],
			['id' =>312,'nombre' => 'INNOCENTI'],
			['id' =>313,'nombre' => 'ISDERA'],
			['id' =>314,'nombre' => 'ISO'],
			['id' =>315,'nombre' => 'ISOTTA-FRASCHINI'],
			['id' =>316,'nombre' => 'JENSEN'],
			['id' =>317,'nombre' => 'JVA'],
			['id' =>318,'nombre' => 'KOENIGSEGG'],
			['id' =>319,'nombre' => 'LADA'],
			['id' =>320,'nombre' => 'LAGONDA'],
			['id' =>321,'nombre' => 'LEYLAND'],
			['id' =>322,'nombre' => 'LISTER'],
			['id' =>323,'nombre' => 'LMX'],
			['id' =>324,'nombre' => 'LOTEC'],
			['id' =>325,'nombre' => 'LUAZ'],
			['id' =>326,'nombre' => 'LLOYD'],
			['id' =>327,'nombre' => 'MAHINDRA'],
			['id' =>328,'nombre' => 'MARCOS'],
			['id' =>329,'nombre' => 'MARTIN'],
			['id' =>330,'nombre' => 'MARUTI'],
			['id' =>331,'nombre' => 'MATRA'],
			['id' =>332,'nombre' => 'McLAREN'],
			['id' =>333,'nombre' => 'MEGA'],
			['id' =>334,'nombre' => 'MINI'],
			['id' =>335,'nombre' => 'MONTEVERDI'],
			['id' =>336,'nombre' => 'MORETTI'],
			['id' =>337,'nombre' => 'MORGAN'],
			['id' =>338,'nombre' => 'MOSKVITCH'],
			['id' =>339,'nombre' => 'NECKAR'],
			['id' =>340,'nombre' => 'NOBLE'],
			['id' =>341,'nombre' => 'NSU'],
			['id' =>342,'nombre' => 'OSCA'],
			['id' =>343,'nombre' => 'PACKARD'],
			['id' =>344,'nombre' => 'PAGANI'],
			['id' =>345,'nombre' => 'PANHARD ET LEVASSOR'],
			['id' =>346,'nombre' => 'PANOZ'],
			['id' =>347,'nombre' => 'PERODUA'],
			['id' =>348,'nombre' => 'PROTON'],
			['id' =>349,'nombre' => 'PUMA'],
			['id' =>350,'nombre' => 'QVALE'],
			['id' =>351,'nombre' => 'RAILEY AND SCOTT'],
			['id' =>352,'nombre' => 'RELIANT'],
			['id' =>353,'nombre' => 'ROCHDALE'],
			['id' =>354,'nombre' => 'SAMSUNG'],
			['id' =>355,'nombre' => 'SCION'],
			['id' =>356,'nombre' => 'SHELBY'],
			['id' =>357,'nombre' => 'SIATA'],
			['id' =>358,'nombre' => 'SIMCA'],
			['id' =>359,'nombre' => 'SKODA'],
			['id' =>360,'nombre' => 'SMART'],
			['id' =>361,'nombre' => 'SSANGYOUNG'],
			['id' =>362,'nombre' => 'SUNBEAM'],
			['id' =>363,'nombre' => 'TALBOT'],
			['id' =>364,'nombre' => 'TATA'],
			['id' =>365,'nombre' => 'TATRA'],
			['id' =>366,'nombre' => 'TORNADO'],
			['id' =>367,'nombre' => 'TRABANT'],
			['id' =>368,'nombre' => 'TUCKER'],
			['id' =>369,'nombre' => 'TURNER'],
			['id' =>370,'nombre' => 'TVR'],
			['id' =>371,'nombre' => 'UAZ'],
			['id' =>372,'nombre' => 'ULTIMA'],
			['id' =>373,'nombre' => 'UMM'],
			['id' =>374,'nombre' => 'VANDEN PLAS'],
			['id' =>375,'nombre' => 'VECTOR'],
			['id' =>376,'nombre' => 'VENTURI'],
			['id' =>377,'nombre' => 'VOLGA'],
			['id' =>378,'nombre' => 'WARTBURG'],
			['id' =>379,'nombre' => 'WILLYS-OVERLAND'],
			['id' =>380,'nombre' => 'WOLSELEY'],
			['id' =>381,'nombre' => 'YUE LOONG'],
			['id' =>382,'nombre' => 'ZAZ'],
			['id' =>383,'nombre' => 'ZIL'],
			['id' =>384,'nombre' => 'EDRA'],
			['id' =>385,'nombre' => 'DAELIM'],
			['id' =>386,'nombre' => 'JUNIOR'],
			['id' =>387,'nombre' => 'K & O'],
			['id' =>388,'nombre' => 'FUDI'],
			['id' =>389,'nombre' => 'KAR-DAR'],
			['id' =>390,'nombre' => 'KEMLITE'],
			['id' =>391,'nombre' => 'KIEFER'],
			['id' =>392,'nombre' => 'KING LONG'],
			['id' =>393,'nombre' => 'KTM'],
			['id' =>394,'nombre' => 'KYMCO'],
			['id' =>395,'nombre' => 'KYNEDYNE'],
			['id' =>396,'nombre' => 'LAHDEN AUTOKORI'],
			['id' =>397,'nombre' => 'LAMBRETTA'],
			['id' =>398,'nombre' => 'LAVERDA'],
			['id' =>399,'nombre' => 'LEER'],
			['id' =>400,'nombre' => 'LEM'],
			['id' =>401,'nombre' => 'LIFAN'],
			['id' =>402,'nombre' => 'LUGARTH'],
			['id' =>403,'nombre' => 'MAGNI'],
			['id' =>404,'nombre' => 'MALAGUTI'],
			['id' =>405,'nombre' => 'MAN'],
			['id' =>406,'nombre' => 'MARCOPOLO'],
			['id' =>407,'nombre' => 'Maxi-Dump'],
			['id' =>408,'nombre' => 'MAXIMA'],
			['id' =>409,'nombre' => 'MAZ'],
			['id' =>410,'nombre' => 'METALPAR'],
			['id' =>411,'nombre' => 'METALSUR'],
			['id' =>412,'nombre' => 'MID BUS'],
			['id' =>413,'nombre' => 'MIDUAL'],
			['id' =>414,'nombre' => 'MIDWEST'],
			['id' =>415,'nombre' => 'MINNEAPOLIS CUSTOM'],
			['id' =>416,'nombre' => 'MM INTERNATIONAL'],
			['id' =>417,'nombre' => 'MOBY DYCK'],
			['id' =>418,'nombre' => 'MOCI'],
			['id' =>419,'nombre' => 'MONDIAL'],
			['id' =>420,'nombre' => 'MORGANCORP'],
			['id' =>421,'nombre' => 'MOTO MORINI'],
			['id' =>422,'nombre' => 'MOTOBECANE'],
			['id' =>423,'nombre' => 'MCI'],
			['id' =>424,'nombre' => 'MOTOR UNION'],
			['id' =>425,'nombre' => 'MOXY'],
			['id' =>426,'nombre' => 'MÜNCH'],
			['id' =>427,'nombre' => 'MV AUGUSTA'],
			['id' =>428,'nombre' => 'MYCSA'],
			['id' =>429,'nombre' => 'MZ / MUZ'],
			['id' =>430,'nombre' => 'NABI'],
			['id' =>431,'nombre' => 'NEOBUS'],
			['id' =>432,'nombre' => 'NEOPLAN'],
			['id' =>433,'nombre' => 'NEW FLYER'],
			['id' =>434,'nombre' => 'NOGE'],
			['id' =>435,'nombre' => 'NORTON'],
			['id' =>436,'nombre' => 'OPTARE'],
			['id' =>437,'nombre' => 'ORION'],
			['id' =>438,'nombre' => 'Overbilt'],
			['id' =>439,'nombre' => 'PACAR'],
			['id' =>440,'nombre' => 'PANZER USA'],
			['id' =>441,'nombre' => 'Parker'],
			['id' =>442,'nombre' => 'PAVLOVO'],
			['id' =>443,'nombre' => 'FISKER'],
			['id' =>444,'nombre' => 'PLAXTON'],
			['id' =>445,'nombre' => 'POLARIS'],
			['id' =>446,'nombre' => 'POLINI'],
			['id' =>447,'nombre' => 'PREVOST'],
			['id' =>448,'nombre' => 'PROCAR'],
			['id' =>449,'nombre' => 'Quality Welding Service'],
			['id' =>450,'nombre' => 'REMOLQUES Y CONVERSIONES'],
			['id' =>451,'nombre' => 'RENO'],
			['id' =>452,'nombre' => 'RIDLEY'],
			['id' =>453,'nombre' => 'RIEJU'],
			['id' =>454,'nombre' => 'ROGERS AND SONS PTY LTD'],
			['id' =>455,'nombre' => 'ROGUE/ATLAS'],
			['id' =>456,'nombre' => 'ROYAL ENFIELD'],
			['id' =>457,'nombre' => 'SALDIVIA'],
			['id' =>458,'nombre' => 'SALVADOR CAETANO'],
			['id' =>459,'nombre' => 'SANMARINO'],
			['id' =>460,'nombre' => 'SANOS'],
			['id' =>461,'nombre' => 'SEGUSA'],
			['id' =>462,'nombre' => 'SETRA'],
			['id' =>463,'nombre' => 'SHERCO'],
			['id' =>464,'nombre' => 'SILLER'],
			['id' =>465,'nombre' => 'SITCAR'],
			['id' =>466,'nombre' => 'SOLARIS'],
			['id' =>467,'nombre' => 'Sooner'],
			['id' =>468,'nombre' => 'Sparta'],
			['id' =>469,'nombre' => 'Specialty Trailer'],
			['id' =>470,'nombre' => 'STARTRANS'],
			['id' =>471,'nombre' => 'SUPERBUS'],
			['id' =>472,'nombre' => 'SUTLEJ'],
			['id' =>473,'nombre' => 'SYM'],
			['id' =>474,'nombre' => 'TACAMAR'],
			['id' =>475,'nombre' => 'TACASU'],
			['id' =>476,'nombre' => 'Take 3'],
			['id' =>477,'nombre' => 'Talbert'],
			['id' =>478,'nombre' => 'TASHER'],
			['id' =>479,'nombre' => 'TECMOVIL'],
			['id' =>480,'nombre' => 'THOMAS'],
			['id' =>481,'nombre' => 'TITAN'],
			['id' =>482,'nombre' => 'Titan Trailers -'],
			['id' =>483,'nombre' => 'TPD Trailers'],
			['id' =>484,'nombre' => 'TRAILKING'],
			['id' =>485,'nombre' => 'Trails West'],
			['id' =>486,'nombre' => 'TrailTech'],
			['id' =>487,'nombre' => 'TRANS-SCHRYVER'],
			['id' =>488,'nombre' => 'Travis'],
			['id' =>489,'nombre' => 'TREMISA'],
			['id' =>490,'nombre' => 'Trout River'],
			['id' =>491,'nombre' => 'TTM'],
			['id' =>492,'nombre' => 'TÜRKKAR'],
			['id' =>493,'nombre' => 'TWIN EAGLE'],
			['id' =>494,'nombre' => 'U.S. Cargo'],
			['id' =>495,'nombre' => 'ULTRA'],
			['id' =>496,'nombre' => 'URAL'],
			['id' =>497,'nombre' => 'URETASA'],
			['id' =>498,'nombre' => 'VANHOOL'],
			['id' =>499,'nombre' => 'VENTO'],
			['id' =>500,'nombre' => 'VICTORY'],
			['id' =>501,'nombre' => 'VOLGREN AUSTRALIA'],
			['id' =>502,'nombre' => 'VOR'],
			['id' =>503,'nombre' => 'VOXAN'],
			['id' =>504,'nombre' => 'Walker'],
			['id' =>505,'nombre' => 'WEBASTO THERMO'],
			['id' =>506,'nombre' => 'Wells Cargo'],
			['id' =>507,'nombre' => 'West Wind'],
			['id' =>508,'nombre' => 'WILD WEST'],
			['id' =>509,'nombre' => 'Winston'],
			['id' =>510,'nombre' => 'WORLD TRANS'],
			['id' =>511,'nombre' => 'WRIGHT'],
			['id' =>512,'nombre' => 'XTRA-MEX'],
			['id' =>513,'nombre' => 'ZASADA'],
			['id' =>514,'nombre' => 'CACCIAMALI'],
			['id' =>515,'nombre' => 'AEON'],
			['id' =>516,'nombre' => 'Beavertail Trailers'],
			['id' =>517,'nombre' => 'BIMOTA'],
			['id' =>518,'nombre' => 'ALEXANDER DENNIS'],
			['id' =>519,'nombre' => 'GAMBLER'],
			['id' =>520,'nombre' => 'GASGAS'],
			['id' =>521,'nombre' => 'GILERA'],
			['id' =>522,'nombre' => 'GLAS'],
			['id' =>523,'nombre' => 'GOSHEN COACH'],
			['id' =>524,'nombre' => 'Aapex Trailer'],
			['id' =>525,'nombre' => 'ACAPULCO'],
			['id' =>526,'nombre' => 'ADACAR FERBEL'],
			['id' =>527,'nombre' => 'ADLER'],
			['id' =>528,'nombre' => 'ADLY'],
			['id' =>529,'nombre' => 'AEROTEK'],
			['id' =>530,'nombre' => 'AGRALE'],
			['id' =>531,'nombre' => 'AGUILAR'],
			['id' =>532,'nombre' => 'AGUIRRE'],
			['id' =>533,'nombre' => 'AJS'],
			['id' =>534,'nombre' => 'ALAN B DENNING ABD'],
			['id' =>535,'nombre' => 'ALCON'],
			['id' =>536,'nombre' => 'ALEK'],
			['id' =>537,'nombre' => 'ALFA'],
			['id' =>538,'nombre' => 'ALONSO'],
			['id' =>539,'nombre' => 'ALLENDE'],
			['id' =>540,'nombre' => 'Allstate Trailers Inc.'],
			['id' =>541,'nombre' => 'AMERICA'],
			['id' =>542,'nombre' => 'AMERICAN IRONHORSE'],
			['id' =>543,'nombre' => 'AMHER'],
			['id' =>544,'nombre' => 'ARQUIMOVIL'],
			['id' =>545,'nombre' => 'ATACA'],
			['id' =>546,'nombre' => 'AZTECA'],
			['id' =>547,'nombre' => 'BALDERAS'],
			['id' =>548,'nombre' => 'BARRERA'],
			['id' =>549,'nombre' => 'BENELLI'],
			['id' =>550,'nombre' => 'BERKHOF JONCKHEERE'],
			['id' =>551,'nombre' => 'BETA'],
			['id' =>552,'nombre' => 'BIG DOG'],
			['id' =>553,'nombre' => 'BLUE BIRD'],
			['id' =>554,'nombre' => 'BOMBARDIER'],
			['id' =>555,'nombre' => 'BONANZA'],
			['id' =>556,'nombre' => 'BORILE'],
			['id' =>557,'nombre' => 'BOVA'],
			['id' =>558,'nombre' => 'BRIGHT COOP, INC'],
			['id' =>559,'nombre' => 'Bri-Mar Trailers'],
			['id' =>560,'nombre' => 'BRITTEN'],
			['id' =>561,'nombre' => 'BSA'],
			['id' =>562,'nombre' => 'BUELL'],
			['id' =>563,'nombre' => 'Built-Rite Trailers'],
			['id' =>564,'nombre' => 'BUS & COACH INTERNATIONAL'],
			['id' =>565,'nombre' => 'BUSAF'],
			['id' =>566,'nombre' => 'BUSSCAR'],
			['id' =>567,'nombre' => 'BUSTOS'],
			['id' =>568,'nombre' => 'CAEMSA'],
			['id' =>569,'nombre' => 'CAGIVA'],
			['id' =>570,'nombre' => 'CALIFORNIA'],
			['id' =>571,'nombre' => 'CALIFORNIA CUSTOMS(CALCUSTOMS)'],
			['id' =>572,'nombre' => 'CAMEZA'],
			['id' =>573,'nombre' => 'CAMPAGNA'],
			['id' =>574,'nombre' => 'CANNONDALE'],
			['id' =>575,'nombre' => 'CAPASA'],
			['id' =>576,'nombre' => 'CARAVAN'],
			['id' =>577,'nombre' => 'CARDENAZ'],
			['id' =>578,'nombre' => 'CARGO'],
			['id' =>579,'nombre' => 'CARROCERIAS REFRIGERADAS'],
			['id' =>580,'nombre' => 'TAMPICO'],
			['id' =>581,'nombre' => 'CARROYUC'],
			['id' =>582,'nombre' => 'CARRUS/VOLVO'],
			['id' =>583,'nombre' => 'CARZA'],
			['id' =>584,'nombre' => 'CASTROSUA'],
			['id' =>585,'nombre' => 'CATAMEX'],
			['id' =>586,'nombre' => 'CAYPROMEMA'],
			['id' =>587,'nombre' => 'CCM'],
			['id' =>588,'nombre' => 'CECA'],
			['id' =>589,'nombre' => 'DINAMO'],
			['id' =>590,'nombre' => 'CMC'],
			['id' =>591,'nombre' => 'Coachcraft Mfg.'],
			['id' =>592,'nombre' => 'CODESI'],
			['id' =>593,'nombre' => 'COLLINS'],
			['id' =>594,'nombre' => 'CONVERSIONES Y CARROCERIAS'],
			['id' =>595,'nombre' => 'CORP. CARROCERA'],
			['id' =>596,'nombre' => 'COYOTE'],
			['id' =>597,'nombre' => 'CRUZ'],
			['id' =>598,'nombre' => 'CUAUHTEMOC'],
			['id' =>599,'nombre' => 'CUELLAR'],
			['id' =>600,'nombre' => 'CUITLAHUAC'],
			['id' =>601,'nombre' => 'CUSTOM COACHES'],
			['id' =>602,'nombre' => 'CYM NACIONAL'],
			['id' =>603,'nombre' => 'CYMA'],
			['id' =>604,'nombre' => 'CYMMET'],
			['id' =>605,'nombre' => 'CHANG'],
			['id' =>606,'nombre' => 'CHANG-MING'],
			['id' =>607,'nombre' => 'CHIAPAS'],
			['id' =>608,'nombre' => 'GEELY'],
			['id' =>609,'nombre' => 'D & B'],
			['id' =>610,'nombre' => 'D¿MARYS'],
			['id' =>611,'nombre' => 'ROKON'],
			['id' =>612,'nombre' => 'DAKOTA MANUFACTURING, INC'],
			['id' =>613,'nombre' => 'DALTO'],
			['id' =>614,'nombre' => 'DALLAVIA'],
			['id' =>615,'nombre' => 'DAYSTAR'],
			['id' =>616,'nombre' => 'DE LA COSTA'],
			['id' =>617,'nombre' => 'DE LUCIO'],
			['id' =>618,'nombre' => 'DEL BAJIO'],
			['id' =>619,'nombre' => 'DEL CARMEN'],
			['id' =>620,'nombre' => 'DEL NORTE'],
			['id' =>621,'nombre' => 'DEL POZZO'],
			['id' =>622,'nombre' => 'DEL SURESTE'],
			['id' =>623,'nombre' => 'DEMSA'],
			['id' =>624,'nombre' => 'DENALI'],
			['id' =>625,'nombre' => 'DESPERADO'],
			['id' =>626,'nombre' => 'DIAZ'],
			['id' =>627,'nombre' => 'DISCAR'],
			['id' =>628,'nombre' => 'Donahue Corporation'],
			['id' =>629,'nombre' => 'Double Delight Trailers'],
			['id' =>630,'nombre' => 'EL DORADO'],
			['id' =>631,'nombre' => 'EL TREBOL'],
			['id' =>632,'nombre' => 'ELCA'],
			['id' =>633,'nombre' => 'ENRIQUEZ'],
			['id' =>634,'nombre' => 'EUROCAR'],
			['id' =>635,'nombre' => 'EUROFRIGO'],
			['id' =>636,'nombre' => 'FENIX'],
			['id' =>637,'nombre' => 'FIJSA'],
			['id' =>638,'nombre' => 'FLORESTA'],
			['id' =>639,'nombre' => 'Foster Premium Trailers'],
			['id' =>640,'nombre' => 'FRANCISCANAS'],
			['id' =>641,'nombre' => 'FREY'],
			['id' =>642,'nombre' => 'FRIGOMOVIL'],
			['id' =>643,'nombre' => 'FRIMAX'],
			['id' =>644,'nombre' => 'FRONTERA'],
			['id' =>645,'nombre' => 'GALLEGOS'],
			['id' =>646,'nombre' => 'GAMEZ'],
			['id' =>647,'nombre' => 'GAMI'],
			['id' =>648,'nombre' => 'GARCIA'],
			['id' =>649,'nombre' => 'GARCIA Y GONZALEZ'],
			['id' =>650,'nombre' => 'GARRIDO'],
			['id' =>651,'nombre' => 'GENERAL DE PERFILES'],
			['id' =>652,'nombre' => 'GHEZZ&BRIAN'],
			['id' =>653,'nombre' => 'GIL AYALA'],
			['id' =>654,'nombre' => 'GILLIG'],
			['id' =>655,'nombre' => 'GLAVAL BUS'],
			['id' =>656,'nombre' => 'GNOME E RHONE'],
			['id' =>657,'nombre' => 'GODINEZ'],
			['id' =>658,'nombre' => 'GONZALEZ'],
			['id' =>659,'nombre' => 'GOOSENECK'],
			['id' =>660,'nombre' => 'GRAHAM'],
			['id' =>661,'nombre' => 'GSM'],
			['id' =>662,'nombre' => 'GUAJARDO'],
			['id' =>663,'nombre' => 'GUERRERO'],
			['id' =>664,'nombre' => 'GUTSA'],
			['id' =>665,'nombre' => 'HEIL'],
			['id' =>666,'nombre' => 'CHANG JIANG'],
			['id' =>667,'nombre' => 'HERCULES'],
			['id' =>668,'nombre' => 'HERCUSA'],
			['id' =>669,'nombre' => 'HOFFMAN'],
			['id' =>670,'nombre' => 'HOLDEN'],
			['id' =>671,'nombre' => 'HUAJUCO'],
			['id' =>672,'nombre' => 'HURTADO'],
			['id' =>673,'nombre' => 'HUSABERG'],
			['id' =>674,'nombre' => 'HUSQVARNA'],
			['id' =>675,'nombre' => 'IARAPUATO'],
			['id' =>676,'nombre' => 'IDER'],
			['id' =>677,'nombre' => 'Ifor Williams Trailers Ltd'],
			['id' =>678,'nombre' => 'IMPALA'],
			['id' =>679,'nombre' => 'INCAMEX'],
			['id' =>680,'nombre' => 'INDUSTRIA METALICA DE CHIAPAS'],
			['id' =>681,'nombre' => 'INMAPECAR'],
			['id' =>682,'nombre' => 'INTERKAMP'],
			['id' =>683,'nombre' => 'INTERSEAL'],
			['id' =>684,'nombre' => 'ISRAEL'],
			['id' =>685,'nombre' => 'JEHOVA'],
			['id' =>686,'nombre' => 'JESCO'],
			['id' =>687,'nombre' => 'JORGHER'],
			['id' =>688,'nombre' => 'KUZZY'],
			['id' =>689,'nombre' => 'LA PIEDAD'],
			['id' =>690,'nombre' => 'LA TROJE'],
			['id' =>691,'nombre' => 'LARA'],
			['id' =>692,'nombre' => 'LEA'],
			['id' =>693,'nombre' => 'LEAL'],
			['id' =>694,'nombre' => 'LEDEZMA'],
			['id' =>695,'nombre' => 'LEMSA'],
			['id' =>696,'nombre' => 'LOBOS'],
			['id' =>697,'nombre' => 'LOPEZ'],
			['id' =>698,'nombre' => 'LOZOYA'],
			['id' =>699,'nombre' => 'LLAMAS'],
			['id' =>700,'nombre' => 'MAQUENSA'],
			['id' =>701,'nombre' => 'MARTINEZ'],
			['id' =>702,'nombre' => 'MAX'],
			['id' =>703,'nombre' => 'MAYITO'],
			['id' =>704,'nombre' => 'MC'],
			['id' =>705,'nombre' => 'MODERNAS'],
			['id' =>706,'nombre' => 'MONTOYA'],
			['id' =>707,'nombre' => 'MORA'],
			['id' =>708,'nombre' => 'NOLACOO'],
			['id' =>709,'nombre' => 'NUÑEZ'],
			['id' =>710,'nombre' => 'OAXACA'],
			['id' =>711,'nombre' => 'OCAMPO'],
			['id' =>712,'nombre' => 'OLIVER'],
			['id' =>713,'nombre' => 'ORDOÑEZ'],
			['id' =>714,'nombre' => 'ORONA'],
			['id' =>715,'nombre' => 'PASEO'],
			['id' =>716,'nombre' => 'PEREA'],
			['id' =>717,'nombre' => 'PETER'],
			['id' =>718,'nombre' => 'PIMENTEL-TAMEZ'],
			['id' =>719,'nombre' => 'PLASTIC DESIGN'],
			['id' =>720,'nombre' => 'PLUS'],
			['id' =>721,'nombre' => 'SOMEX/MASA'],
			['id' =>722,'nombre' => 'PRIETO'],
			['id' =>723,'nombre' => 'PROACERO'],
			['id' =>724,'nombre' => 'PROMAIN'],
			['id' =>725,'nombre' => 'QRTRO'],
			['id' =>726,'nombre' => 'RAMIREZ CARROCERIAS'],
			['id' =>727,'nombre' => 'RAYMSA'],
			['id' =>728,'nombre' => 'REMADA'],
			['id' =>729,'nombre' => 'RHC'],
			['id' =>730,'nombre' => 'RITSCHARR'],
			['id' =>731,'nombre' => 'ROBLEDO'],
			['id' =>732,'nombre' => 'ROCHA'],
			['id' =>733,'nombre' => 'RODAL'],
			['id' =>734,'nombre' => 'RUANO'],
			['id' =>735,'nombre' => 'RUIZ'],
			['id' =>736,'nombre' => 'RYO'],
			['id' =>737,'nombre' => 'SAN ROBERTO'],
			['id' =>738,'nombre' => 'SANDOVAL'],
			['id' =>739,'nombre' => 'SERVAL'],
			['id' =>740,'nombre' => 'SOLCAR'],
			['id' =>741,'nombre' => 'SORIA'],
			['id' =>742,'nombre' => 'SOTOMEX'],
			['id' =>743,'nombre' => 'TADEOS'],
			['id' =>744,'nombre' => 'TANGAMANGA'],
			['id' =>745,'nombre' => 'TAURO'],
			['id' =>746,'nombre' => 'TERAN'],
			['id' =>747,'nombre' => 'THERMOKING'],
			['id' =>748,'nombre' => 'TOLUCA'],
			['id' =>749,'nombre' => 'TORRESBACA'],
			['id' =>750,'nombre' => 'TRACTORENOVA'],
			['id' =>751,'nombre' => 'TRANSFREZZER'],
			['id' =>752,'nombre' => 'TRANSFRIO'],
			['id' =>753,'nombre' => 'TREVIÑO'],
			['id' =>754,'nombre' => 'TULANCINGO'],
			['id' =>755,'nombre' => 'URIVERA'],
			['id' =>756,'nombre' => 'VALENCIA'],
			['id' =>757,'nombre' => 'VALENZUELA'],
			['id' =>758,'nombre' => 'VENEGAS'],
			['id' =>759,'nombre' => 'VILCHIS'],
			['id' =>760,'nombre' => 'VILLASEÑOR'],
			['id' =>761,'nombre' => 'VILLEGAS'],
			['id' =>762,'nombre' => 'VRC'],
			['id' =>763,'nombre' => 'WONG'],
			['id' =>764,'nombre' => 'YUNQUE'],
			['id' =>765,'nombre' => 'ZAMEX'],
			['id' =>766,'nombre' => 'ZAPATA'],
			['id' =>767,'nombre' => 'Century Trailer'],
			['id' =>768,'nombre' => 'SPYKER'],
			['id' =>769,'nombre' => 'MBK'],
			['id' =>770,'nombre' => 'SVO'],
			['id' =>771,'nombre' => 'AIL'],
			['id' =>772,'nombre' => 'JINCHENG'],
			['id' =>773,'nombre' => 'DONG TIAN'],
			['id' =>774,'nombre' => 'EXILE CYCLES'],
			['id' =>775,'nombre' => 'HSV'],
			['id' =>776,'nombre' => 'GAZ'],
			['id' =>777,'nombre' => 'ZHEJIANG/VISITAASIASCOOTER'],
			['id' =>778,'nombre' => 'TANK'],
			['id' =>779,'nombre' => 'MAYBACH'],
			['id' =>780,'nombre' => 'UD'],
			['id' =>781,'nombre' => 'FUSO'],
			['id' =>782,'nombre' => 'TOROMEX'],
			['id' =>783,'nombre' => 'ZANETTI'],
			['id' =>784,'nombre' => 'SSC'],
			['id' =>785,'nombre' => 'ROXON'],
			['id' =>786,'nombre' => 'FODEN'],
			['id' =>787,'nombre' => 'KAMAJI'],
			['id' =>788,'nombre' => 'ARGO'],
			['id' =>789,'nombre' => 'CENTAUR'],
			['id' =>790,'nombre' => 'MAG'],
			['id' =>791,'nombre' => 'FOREST RIVER'],
			['id' =>792,'nombre' => 'CARGO-MATE'],
			['id' =>793,'nombre' => 'STARCRAFT'],
			['id' =>794,'nombre' => 'FLEETWOOD'],
			['id' =>795,'nombre' => 'TORO'],
			['id' =>796,'nombre' => 'EZGO'],
			['id' =>797,'nombre' => 'GIANT'],
			['id' =>798,'nombre' => 'GULFSTREAM'],
			['id' =>799,'nombre' => 'NMC'],
			['id' =>800,'nombre' => 'BENGALA'],
			['id' =>801,'nombre' => 'SUKIDA'],
			['id' =>802,'nombre' => 'LONCIN'],
			['id' =>803,'nombre' => 'LEIKE'],
			['id' =>804,'nombre' => 'BLUEBIRD'],
			['id' =>805,'nombre' => 'EAGER BEAVER'],
			['id' =>806,'nombre' => 'EAST'],
			['id' =>807,'nombre' => 'FONTAINE'],
			['id' =>808,'nombre' => 'GREAT DANE'],
			['id' =>809,'nombre' => 'KENTUCKY'],
			['id' =>811,'nombre' => 'PACE AMERICAN'],
			['id' =>812,'nombre' => 'STOUGHTON'],
			['id' =>813,'nombre' => 'STRICK'],
			['id' =>815,'nombre' => 'TRAIL KING'],
			['id' =>816,'nombre' => 'TRANSCRAFT'],
			['id' =>817,'nombre' => 'WABASH NATIONAL'],
			['id' =>819,'nombre' => 'DINLI'],
			['id' =>820,'nombre' => 'DREAM'],
			['id' =>821,'nombre' => 'DUBAY'],
			['id' =>822,'nombre' => 'E-TON'],
			['id' =>823,'nombre' => 'HYOSUNG'],
			['id' =>824,'nombre' => 'KINETIC'],
			['id' =>825,'nombre' => 'LML'],
			['id' =>826,'nombre' => 'TVS'],
			['id' =>827,'nombre' => 'MUTANT'],
			['id' =>828,'nombre' => 'SEADOO'],
			['id' =>829,'nombre' => 'UM'],
			['id' =>830,'nombre' => 'ARCTIC CAT'],
			['id' =>831,'nombre' => 'BKM'],
			['id' =>832,'nombre' => 'DISCOVER'],
			['id' =>833,'nombre' => 'IZUKA'],
			['id' =>834,'nombre' => 'VISAO'],
			['id' =>835,'nombre' => 'CHERY'],
			['id' =>836,'nombre' => 'DERBI'],
			['id' =>837,'nombre' => 'HUMBER'],
			['id' =>838,'nombre' => 'ITALIKA'],
			['id' =>839,'nombre' => 'SUNDIRO'],
			['id' =>840,'nombre' => 'ANENS S.A. DE C.V.'],
			['id' =>841,'nombre' => 'ADEMES Y MAQUINARIA DE CUAUHTEMOC SA CV'],
			['id' =>842,'nombre' => 'AUTOS ESPECIALES DE MEXICO SA DE CV'],
			['id' =>843,'nombre' => 'AIH'],
			['id' =>844,'nombre' => 'AGROQUIMICA DEL NORTE'],
			['id' =>845,'nombre' => 'AUTOMOTRIZ PEYCHA SA DE CV'],
			['id' =>846,'nombre' => 'A CANC'],
			['id' =>847,'nombre' => 'REMOLQUES AZTECA'],
			['id' =>848,'nombre' => 'BAYKAL'],
			['id' =>849,'nombre' => 'BRONCO'],
			['id' =>850,'nombre' => 'BEPENSA'],
			['id' =>851,'nombre' => 'BARRUCHI'],
			['id' =>852,'nombre' => 'CAN-AM'],
			['id' =>853,'nombre' => 'CREACIONES AUTOMOTRICES NACIONALES'],
			['id' =>854,'nombre' => 'COMERCIAL TRACTOCAR DEL NORTE SA DE CV'],
			['id' =>855,'nombre' => 'CUSHMAN'],
			['id' =>856,'nombre' => 'CATEGORIA UNICA'],
			['id' =>857,'nombre' => 'DEMOSTRACION'],
			['id' =>858,'nombre' => 'DE SOTO'],
			['id' =>859,'nombre' => 'ANDATI'],
			['id' =>860,'nombre' => 'EBY'],
			['id' =>861,'nombre' => 'ESCORT'],
			['id' =>862,'nombre' => 'EUROMOTOS'],
			['id' =>863,'nombre' => 'FEDERTRAC'],
			['id' =>864,'nombre' => 'FAW'],
			['id' =>865,'nombre' => 'GEM'],
			['id' =>866,'nombre' => 'GRUPO IND. TRES ESTRELLAS SA CV'],
			['id' =>867,'nombre' => 'EL GORDO'],
			['id' =>868,'nombre' => 'GRUPO RUVESA'],
			['id' =>869,'nombre' => 'GREAT TIMBER'],
			['id' =>870,'nombre' => 'GPO REM DEL NORTE SACV'],
			['id' =>871,'nombre' => 'GEXA S A DE C V'],
			['id' =>872,'nombre' => 'HAULMARK'],
			['id' =>873,'nombre' => 'HAOQING'],
			['id' =>874,'nombre' => 'INDUSTRIAS AGRICOLAS OLFERT SA DE CV'],
			['id' =>875,'nombre' => 'INDUSTRIAS BANMAN SA DE CV'],
			['id' =>876,'nombre' => 'INDUSTRIAS AGRICOLAS DYCK'],
			['id' =>877,'nombre' => 'IMPLEMENTOS AGRICOLAS ENNS'],
			['id' =>878,'nombre' => 'INMOBILIARIA GARE DEL LITORAL SA DE CV'],
			['id' =>879,'nombre' => 'INTRAMET'],
			['id' =>880,'nombre' => 'IMPLEMENTOS BANENS SA CV'],
			['id' =>881,'nombre' => 'INDUSTRIAS METALICAS TAURUS'],
			['id' =>882,'nombre' => 'INDUSTRIAS GONZALEZ SA DE CV'],
			['id' =>883,'nombre' => 'JMG'],
			['id' =>884,'nombre' => 'KIA'],
			['id' =>885,'nombre' => 'KILOTON'],
			['id' =>886,'nombre' => 'KAPPER'],
			['id' =>887,'nombre' => 'KARAVAN'],
			['id' =>888,'nombre' => 'LAMBRO'],
			['id' =>889,'nombre' => 'INDUSTRIAS LUGARTH SA DE CV'],
			['id' =>891,'nombre' => 'MANUFACTURAS INDUSTRIALES GAMI'],
			['id' =>892,'nombre' => 'MERKUR'],
			['id' =>893,'nombre' => 'MOTORES Y ADAPTACIONES SA DE CV'],
			['id' =>894,'nombre' => 'MAPOSA'],
			['id' =>895,'nombre' => 'MGR MEXICO SA DE CV'],
			['id' =>896,'nombre' => 'MASTER ROAD'],
			['id' =>897,'nombre' => 'META'],
			['id' =>898,'nombre' => 'IMPORTADORA Y COMERCIALIZADORA NEUFELD'],
			['id' =>899,'nombre' => 'NORTE E IMPLEMENTOS'],
			['id' =>900,'nombre' => 'INDUSTRIAS DEL NORTE DE CUAUHTEMOC SA CV'],
			['id' =>901,'nombre' => 'NATSA'],
			['id' =>902,'nombre' => 'RODARE'],
			['id' =>903,'nombre' => 'OJEDA MOTORS'],
			['id' =>904,'nombre' => 'OTRAS MARCAS'],
			['id' =>905,'nombre' => 'CHASIS Y AUTOPARTES OSHMEX SA CV'],
			['id' =>906,'nombre' => 'OTTAWA'],
			['id' =>907,'nombre' => 'PLATAFORMAS Y REMOLQUES CUAUHTEMOC'],
			['id' =>909,'nombre' => 'PJ TRAILER'],
			['id' =>910,'nombre' => 'APRISSA'],
			['id' =>911,'nombre' => 'POTENZA'],
			['id' =>912,'nombre' => 'PLATA YLLANES SA DE CV'],
			['id' =>913,'nombre' => 'RED NECK'],
			['id' =>914,'nombre' => 'CARROCERIAS GRECER'],
			['id' =>915,'nombre' => 'REIMER'],
			['id' =>916,'nombre' => 'ROAD KING DE MEXICO SA DE CV'],
			['id' =>917,'nombre' => 'REMOLQUES SA'],
			['id' =>918,'nombre' => 'REMOLQUES NACIONALES S A'],
			['id' =>919,'nombre' => 'REMOLQUES PANCHO'],
			['id' =>920,'nombre' => 'REMOLQUES TACHO'],
			['id' =>921,'nombre' => 'REMOLQUES MUNOZ'],
			['id' =>922,'nombre' => 'SHERPA'],
			['id' =>923,'nombre' => 'SINSKI'],
			['id' =>924,'nombre' => 'SASAKI'],
			['id' =>925,'nombre' => 'EL SOL'],
			['id' =>926,'nombre' => 'SCOOTY'],
			['id' =>927,'nombre' => 'SEAHAWK'],
			['id' =>928,'nombre' => 'SAYTO'],
			['id' =>929,'nombre' => 'CARROCERIAS SUMA'],
			['id' =>930,'nombre' => 'BATAM'],
			['id' =>931,'nombre' => 'TRACTOCARROCERIAS ACA SA DE CV'],
			['id' =>932,'nombre' => 'TRAKDIESEL DEL NORTE'],
			['id' =>933,'nombre' => 'TRAKSOMEX'],
			['id' =>934,'nombre' => 'TOMOS'],
			['id' =>935,'nombre' => 'TYTANK'],
			['id' =>936,'nombre' => 'TYRRSA'],
			['id' =>937,'nombre' => 'TRACTOCAZA'],
			['id' =>938,'nombre' => 'VICTOR PATRON'],
			['id' =>939,'nombre' => 'WOLF'],
			['id' =>940,'nombre' => 'W W TRILER'],
			['id' =>941,'nombre' => 'XENON'],
			['id' =>942,'nombre' => 'YUAN YUAN'],
			['id' =>943,'nombre' => 'APACHE'],
			['id' =>944,'nombre' => 'KASAM'],
			['id' =>945,'nombre' => 'FOTON'],
			['id' =>946,'nombre' => 'KURAZAI'],
			['id' =>947,'nombre' => 'IVECO'],
			['id' =>948,'nombre' => 'MOSLER'],
			['id' =>949,'nombre' => 'SACHS'],
			['id' =>951,'nombre' => 'XCESS'],
			['id' =>952,'nombre' => 'RAM'],
			['id' =>953,'nombre' => 'KINGS'],
			['id' =>954,'nombre' => 'MOTOMEL']
        ]);
    }
}
